---
plugin:
  id: "phate-analysis"
  name: "PHATE Analysis"
  description: "PHATE (Potential of Heat-diffusion for Affinity-based Trajectory Embedding) for dimensionality reduction"
  version: "1.0.0"
  author: "CauldronGO Team"
  category: "analysis"
  icon: "timeline"
  repository: "https://github.com/noatgnu/phate-analysis-plugin"

runtime:
  environments: ["python"]
  entrypoint: "phate_analysis.py"

inputs:
  - name: "input_file"
    label: "Input File"
    type: "file"
    required: true
    accept: ".csv,.tsv,.txt"
    description: "Data matrix file containing samples and measurements"

  - name: "annotation_file"
    label: "Sample Annotation File"
    type: "file"
    required: true
    accept: ".csv,.tsv,.txt"
    description: "Annotation file with Sample column specifying which columns to analyze, plus Condition/Batch for grouping"
    disableAnnotationManagement: true

  - name: "n_components"
    label: "Number of Components"
    type: "number"
    required: true
    default: 2
    min: 2
    max: 10
    step: 1
    description: "Number of PHATE components to compute"

  - name: "log2"
    label: "Apply Log2 Transform"
    type: "boolean"
    default: false
    description: "Apply log2 transformation to the data before PHATE"

  - name: "cluster_method"
    label: "Clustering Method"
    type: "select"
    required: false
    default: "none"
    options:
      - "none"
      - "kmeans"
      - "dbscan"
    description: "Method to detect clusters from PHATE embeddings"

  - name: "auto_k"
    label: "Auto-detect Cluster Count"
    type: "boolean"
    default: false
    description: "Automatically determine optimal number of clusters using elbow method"
    visibleWhen:
      field: "cluster_method"
      equals: "kmeans"

  - name: "n_clusters"
    label: "Number of Clusters"
    type: "number"
    required: false
    default: 5
    min: 2
    max: 20
    step: 1
    description: "Number of clusters for KMeans clustering (ignored if auto-detect is enabled)"
    visibleWhen:
      field: "cluster_method"
      equals: "kmeans"

  - name: "max_k"
    label: "Max Clusters to Test"
    type: "number"
    required: false
    default: 10
    min: 3
    max: 30
    step: 1
    description: "Maximum number of clusters to test for elbow method"
    visibleWhen:
      field: "auto_k"
      equals: true

  - name: "dbscan_eps"
    label: "DBSCAN Epsilon"
    type: "number"
    required: false
    default: 0.5
    min: 0.01
    max: 10
    step: 0.01
    description: "Maximum distance between samples for DBSCAN neighborhood"
    visibleWhen:
      field: "cluster_method"
      equals: "dbscan"

  - name: "dbscan_min_samples"
    label: "DBSCAN Min Samples"
    type: "number"
    required: false
    default: 5
    min: 2
    max: 50
    step: 1
    description: "Minimum number of samples in a neighborhood for DBSCAN core points"
    visibleWhen:
      field: "cluster_method"
      equals: "dbscan"

outputs:
  - name: "phate_output"
    path: "phate_output.txt"
    type: "data"
    description: "PHATE coordinates for each sample"
    format: "tsv"

  - name: "phate_3d"
    path: "phate_3d.html"
    type: "html"
    description: "Interactive 3D PHATE visualization (generated when n_components=3)"
    format: "html"

  - name: "elbow_plot"
    path: "elbow_plot.html"
    type: "html"
    description: "Elbow plot for optimal cluster count (generated when auto_k is enabled)"
    format: "html"

annotation:
  annotationFile: "annotation_file"

plots:
  - id: "phate-scatter-condition"
    name: "PHATE Plot (by Condition)"
    type: "scatter"
    dataSource: "phate_output"
    default: true
    config:
      axes:
        x: "x_phate"
        y: "y_phate"
        z: "z_phate"
        colorBy: "condition"
        labels: "sample"

    customization:
      - name: "title"
        label: "Plot Title"
        type: "text"
        default: ""

      - name: "showGrid"
        label: "Show Grid"
        type: "boolean"
        default: true

      - name: "markerSize"
        label: "Marker Size"
        type: "number"
        default: 10
        min: 1
        max: 50

      - name: "width"
        label: "Width (px)"
        type: "number"
        default: 800
        min: 400
        max: 2000

      - name: "height"
        label: "Height (px)"
        type: "number"
        default: 600
        min: 400
        max: 2000

      - name: "marginTop"
        label: "Margin Top (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginRight"
        label: "Margin Right (px)"
        type: "number"
        default: 100
        min: 0
        max: 300

      - name: "marginBottom"
        label: "Margin Bottom (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginLeft"
        label: "Margin Left (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

  - id: "phate-scatter-cluster"
    name: "PHATE Plot (by Cluster)"
    type: "scatter"
    dataSource: "phate_output"
    description: "PHATE scatter plot colored by detected clusters"
    config:
      axes:
        x: "x_phate"
        y: "y_phate"
        z: "z_phate"
        colorBy: "cluster"
        labels: "sample"

    customization:
      - name: "title"
        label: "Plot Title"
        type: "text"
        default: ""

      - name: "showGrid"
        label: "Show Grid"
        type: "boolean"
        default: true

      - name: "markerSize"
        label: "Marker Size"
        type: "number"
        default: 10
        min: 1
        max: 50

      - name: "width"
        label: "Width (px)"
        type: "number"
        default: 800
        min: 400
        max: 2000

      - name: "height"
        label: "Height (px)"
        type: "number"
        default: 600
        min: 400
        max: 2000

      - name: "marginTop"
        label: "Margin Top (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginRight"
        label: "Margin Right (px)"
        type: "number"
        default: 100
        min: 0
        max: 300

      - name: "marginBottom"
        label: "Margin Bottom (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginLeft"
        label: "Margin Left (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

execution:
  argsMapping:
    input_file: "--input_file"
    annotation_file: "--annotation_file"
    n_components: "--n_components"
    log2:
      flag: "--log2"
      when: "true"
    cluster_method: "--cluster_method"
    auto_k:
      flag: "--auto_k"
      when: "true"
    n_clusters: "--n_clusters"
    max_k: "--max_k"
    dbscan_eps: "--dbscan_eps"
    dbscan_min_samples: "--dbscan_min_samples"

  outputDir: "--output_folder"

  requirements:
    python: ">=3.11"
    packages:
      - "numpy>=1.24.0"
      - "pandas>=2.0.0"
      - "phate>=1.0.0"
      - "matplotlib>=3.7.0"
      - "scikit-learn>=1.3.0"
      - "plotly>=5.18.0"

example:
  enabled: true
  values:
    input_file: "diann/imputed.data.txt"
    annotation_file: "diann/annotation.txt"
    n_components: 3
    log2: true
    cluster_method: "kmeans"
    auto_k: true
    max_k: 6
