---
plugin:
  id: "phate-analysis"
  name: "PHATE Analysis"
  description: "PHATE (Potential of Heat-diffusion for Affinity-based Trajectory Embedding) for dimensionality reduction"
  version: "1.0.0"
  author: "CauldronGO Team"
  category: "analysis"
  icon: "timeline"
  repository: "https://github.com/noatgnu/phate-analysis-plugin"

runtime:
  environments: ["python"]
  entrypoint: "phate_analysis.py"

inputs:
  - name: "input_file"
    label: "Input File"
    type: "file"
    required: true
    accept: ".csv,.tsv,.txt"
    description: "Data matrix file containing samples and measurements"

  - name: "annotation_file"
    label: "Sample Annotation File"
    type: "file"
    required: false
    accept: ".csv,.tsv,.txt"
    description: "Optional annotation file for sample grouping and coloring (Sample, Condition, Batch, Color)"

  - name: "columns_name"
    label: "Sample Columns"
    type: "column-selector"
    required: true
    multiple: true
    sourceFile: "input_file"
    description: "Select columns containing sample data for PHATE analysis"

  - name: "n_components"
    label: "Number of Components"
    type: "number"
    required: true
    default: 2
    min: 2
    max: 10
    step: 1
    description: "Number of PHATE components to compute"

  - name: "log2"
    label: "Apply Log2 Transform"
    type: "boolean"
    default: false
    description: "Apply log2 transformation to the data before PHATE"

  - name: "cluster_method"
    label: "Clustering Method"
    type: "select"
    required: false
    default: "none"
    options:
      - "none"
      - "kmeans"
      - "dbscan"
    description: "Method to detect clusters from PHATE embeddings"

  - name: "n_clusters"
    label: "Number of Clusters"
    type: "number"
    required: false
    default: 5
    min: 2
    max: 20
    step: 1
    description: "Number of clusters for KMeans clustering"
    visibleWhen:
      field: "cluster_method"
      equals: "kmeans"

  - name: "dbscan_eps"
    label: "DBSCAN Epsilon"
    type: "number"
    required: false
    default: 0.5
    min: 0.01
    max: 10
    step: 0.01
    description: "Maximum distance between samples for DBSCAN neighborhood"
    visibleWhen:
      field: "cluster_method"
      equals: "dbscan"

  - name: "dbscan_min_samples"
    label: "DBSCAN Min Samples"
    type: "number"
    required: false
    default: 5
    min: 2
    max: 50
    step: 1
    description: "Minimum number of samples in a neighborhood for DBSCAN core points"
    visibleWhen:
      field: "cluster_method"
      equals: "dbscan"

outputs:
  - name: "phate_output"
    path: "phate_output.txt"
    type: "data"
    description: "PHATE coordinates for each sample"
    format: "tsv"

annotation:
  samplesFrom: "columns_name"
  annotationFile: "annotation_file"

plots:
  - id: "phate-scatter-condition"
    name: "PHATE Plot (by Condition)"
    type: "scatter"
    dataSource: "phate_output"
    default: true
    config:
      axes:
        x: "x_phate"
        y: "y_phate"
        z: "z_phate"
        colorBy: "condition"
        labels: "sample"

    customization:
      - name: "title"
        label: "Plot Title"
        type: "text"
        default: ""

      - name: "showGrid"
        label: "Show Grid"
        type: "boolean"
        default: true

      - name: "markerSize"
        label: "Marker Size"
        type: "number"
        default: 10
        min: 1
        max: 50

      - name: "width"
        label: "Width (px)"
        type: "number"
        default: 800
        min: 400
        max: 2000

      - name: "height"
        label: "Height (px)"
        type: "number"
        default: 600
        min: 400
        max: 2000

      - name: "marginTop"
        label: "Margin Top (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginRight"
        label: "Margin Right (px)"
        type: "number"
        default: 100
        min: 0
        max: 300

      - name: "marginBottom"
        label: "Margin Bottom (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginLeft"
        label: "Margin Left (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

  - id: "phate-scatter-cluster"
    name: "PHATE Plot (by Cluster)"
    type: "scatter"
    dataSource: "phate_output"
    description: "PHATE scatter plot colored by detected clusters"
    config:
      axes:
        x: "x_phate"
        y: "y_phate"
        z: "z_phate"
        colorBy: "cluster"
        labels: "sample"

    customization:
      - name: "title"
        label: "Plot Title"
        type: "text"
        default: ""

      - name: "showGrid"
        label: "Show Grid"
        type: "boolean"
        default: true

      - name: "markerSize"
        label: "Marker Size"
        type: "number"
        default: 10
        min: 1
        max: 50

      - name: "width"
        label: "Width (px)"
        type: "number"
        default: 800
        min: 400
        max: 2000

      - name: "height"
        label: "Height (px)"
        type: "number"
        default: 600
        min: 400
        max: 2000

      - name: "marginTop"
        label: "Margin Top (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginRight"
        label: "Margin Right (px)"
        type: "number"
        default: 100
        min: 0
        max: 300

      - name: "marginBottom"
        label: "Margin Bottom (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

      - name: "marginLeft"
        label: "Margin Left (px)"
        type: "number"
        default: 100
        min: 0
        max: 200

execution:
  argsMapping:
    input_file: "--input_file"
    columns_name:
      flag: "--columns_name"
      transform: "comma-join"
    n_components: "--n_components"
    log2:
      flag: "--log2"
      when: "true"
    cluster_method: "--cluster_method"
    n_clusters: "--n_clusters"
    dbscan_eps: "--dbscan_eps"
    dbscan_min_samples: "--dbscan_min_samples"

  outputDir: "--output_folder"

  requirements:
    python: ">=3.11"
    packages:
      - "numpy>=1.24.0"
      - "pandas>=2.0.0"
      - "phate>=1.0.0"
      - "matplotlib>=3.7.0"
      - "scikit-learn>=1.3.0"

example:
  enabled: true
  values:
    input_file: "diann/imputed.data.txt"
    columns_name_source: "diann/imputed.data.txt"
    columns_name:
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-IP_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-IP_02.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-IP_03.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-MockIP_01.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-MockIP_02.raw'
      - 'C:\Raja\DIA-NN searches\June 2022\LT-CBQCA-Test_DIA\RN-DS_220106_BCA_LT-MockIP_03.raw'
    n_components: 2
    log2: true
